{
 "title": "Production",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory (bytes)",
   "type": "graph",
   "description": "Memory (bytes)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "memory_bytes{app=\"find-prod\"}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "description": "find-prod CPU Percentage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu{app=\"find-prod\"}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "memory_utilization{app=\"find-prod\"}"
    }
   ]
  }
 ]
}